baseurl = "https://vickylim.com"
googleAnalytics = "UA-129783867-2"
title = "Vicky Lim"
theme = "cactus"

[Params]
    mainSections = ["post"]
    intro = true
    headline = "My headline"
    description = "Hello. Welcome to my site."
    github = "https://github.com/vickylim"
    linkedin = "https://www.linkedin.com/in/vicky-lim/"
    opengraph = true
    shareLinkedIn = true
    dateFormat = "Mon, Jan 2, 2006"
    rss = true
    colortheme = "classic"

[[params.social]]
  name = "github"
  link = "https://github.com/vickylim"

[[params.social]]
  name = "linkedin"
  link = "https://www.linkedin.com/in/vicky-lim/"

[params]
  [params.comments]
    enabled = true
    # engine = "disqus" # in progress

[Permalinks]
    post = "/:year/:month/:title/"

